-- Clear existing destinations
DELETE FROM destinations;

-- Insert global destinations across continents

-- ASIA - Southeast Asia
INSERT INTO destinations (name, location, description, image_url, tags, average_cost_min, average_cost_max, best_time_start, best_time_end, vibe_type, authenticity_score, popularity_score, yearly_visitors_estimate, is_hidden_gem, activities) VALUES
('Bali', 'Indonesia', 'The Island of the Gods offering perfect beaches, ancient temples, vibrant culture, and world-class surfing spots.', 'https://images.pexels.com/photos/1287460/pexels-photo-1287460.jpeg', ARRAY['Beach', 'Cultural', 'Surfing', 'Wellness'], 800, 2500, 'April', 'October', 'Tropical Paradise', 88, 75, '6 million', false, ARRAY['Surfing', 'Temple visits', 'Yoga', 'Beach', 'Rice terraces']),
('Angkor Wat', 'Siem Reap, Cambodia', 'The worlds largest religious monument, a stunning 12th-century temple complex surrounded by jungle.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Cultural', 'Historical', 'Photography'], 400, 1200, 'November', 'March', 'Ancient Wonder', 95, 70, '2.5 million', false, ARRAY['Temple exploration', 'Sunrise photography', 'Cultural tours', 'History']),
('Ha Long Bay', 'Vietnam', 'UNESCO World Heritage site with thousands of limestone karsts rising from emerald waters.', 'https://images.pexels.com/photos/17078916/pexels-photo-17078916.jpeg', ARRAY['Nature', 'Cruise', 'Adventure'], 300, 800, 'October', 'April', 'Natural Wonder', 90, 68, '4 million', false, ARRAY['Cruising', 'Kayaking', 'Cave exploration', 'Photography']),
('Luang Prabang', 'Laos', 'A serene UNESCO town blending French colonial architecture with Buddhist temples and morning alms ceremonies.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Cultural', 'Spiritual', 'Colonial'], 250, 600, 'November', 'February', 'Serene Heritage', 94, 25, '500,000', true, ARRAY['Temple visits', 'Alms ceremony', 'Waterfalls', 'Night market']),
('Komodo Island', 'Indonesia', 'Home to the legendary Komodo dragons and pristine diving spots in a dramatic volcanic landscape.', 'https://images.pexels.com/photos/17078916/pexels-photo-17078916.jpeg', ARRAY['Wildlife', 'Diving', 'Adventure'], 500, 1500, 'April', 'November', 'Wildlife Adventure', 91, 55, '200,000', false, ARRAY['Dragon spotting', 'Diving', 'Hiking', 'Wildlife photography']),
('Bagan', 'Myanmar', 'Over 2,000 ancient temples scattered across a dusty plain, offering magical sunrise and sunset views.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Historical', 'Spiritual', 'Photography'], 300, 700, 'November', 'February', 'Ancient Plains', 97, 30, '300,000', true, ARRAY['Temple exploration', 'Hot air balloon', 'Photography', 'Cultural immersion']),

-- ASIA - East Asia
('Kyoto', 'Japan', 'Japans cultural capital with ancient temples, Zen gardens, traditional geisha districts, and stunning cherry blossoms.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Cultural', 'Historical', 'Traditional'], 1000, 3000, 'March', 'May', 'Cultural Heart', 92, 72, '50 million', false, ARRAY['Temple visits', 'Garden tours', 'Geisha experiences', 'Tea ceremonies']),
('Zhangjiajie', 'Hunan, China', 'Towering sandstone pillars that inspired Avatars floating mountains, with glass bridges and scenic hikes.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Nature', 'Adventure', 'Photography'], 400, 900, 'April', 'October', 'Avatar Mountains', 89, 50, '10 million', false, ARRAY['Hiking', 'Glass bridge', 'Photography', 'Cable car rides']),
('Jeju Island', 'South Korea', 'Volcanic island with dramatic landscapes, lava tubes, hiking trails, and unique Haenyo divers.', 'https://images.pexels.com/photos/1287460/pexels-photo-1287460.jpeg', ARRAY['Nature', 'Hiking', 'Beach'], 600, 1500, 'April', 'June', 'Volcanic Beauty', 87, 62, '15 million', false, ARRAY['Hiking', 'Beach', 'Museum visits', 'Diving']),
('Tigers Nest Monastery', 'Bhutan', 'A sacred monastery perched on a cliff 900m above the Paro Valley, a spiritual trekking destination.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Spiritual', 'Hiking', 'Cultural'], 800, 2000, 'March', 'May', 'Sacred Heights', 98, 20, '150,000', true, ARRAY['Pilgrimage', 'Hiking', 'Meditation', 'Cultural tours']),

-- EUROPE - Western Europe
('Santorini', 'Greece', 'Iconic white-washed villages perched on volcanic cliffs with legendary sunsets over the Aegean Sea.', 'https://images.pexels.com/photos/1287460/pexels-photo-1287460.jpeg', ARRAY['Beach', 'Romantic', 'Photography'], 1500, 4000, 'April', 'October', 'Island Romance', 85, 78, '2 million', false, ARRAY['Sunset watching', 'Beach', 'Wine tasting', 'Boat tours']),
('Amalfi Coast', 'Italy', 'Dramatic coastline with colorful villages clinging to cliffs, lemon groves, and Mediterranean charm.', 'https://images.pexels.com/photos/1287460/pexels-photo-1287460.jpeg', ARRAY['Coastal', 'Romantic', 'Cultural'], 2000, 5000, 'May', 'September', 'Coastal Glamour', 84, 74, '5 million', false, ARRAY['Scenic drives', 'Beach', 'Hiking', 'Italian cuisine']),
('Swiss Alps', 'Switzerland', 'Majestic mountain peaks, pristine ski resorts, and charming alpine villages year-round.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Mountain', 'Skiing', 'Nature'], 2000, 6000, 'December', 'March', 'Alpine Majesty', 86, 76, '10 million', false, ARRAY['Skiing', 'Hiking', 'Scenic trains', 'Mountain climbing']),
('Hallstatt', 'Austria', 'A fairytale lakeside village with Alpine houses, salt mines, and stunning mountain reflections.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Village', 'Cultural', 'Photography'], 1000, 2500, 'May', 'October', 'Fairytale Village', 92, 65, '1 million', false, ARRAY['Salt mine tours', 'Lake cruises', 'Photography', 'Hiking']),
('Loire Valley', 'France', 'The Garden of France with magnificent chteaux, vineyards, and Renaissance architecture.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Historical', 'Wine', 'Architecture'], 1200, 3500, 'April', 'October', 'Chteau Country', 90, 55, '3 million', false, ARRAY['Castle tours', 'Wine tasting', 'Cycling', 'Hot air ballooning']),

-- EUROPE - Northern Europe
('Northern Lights in Troms', 'Norway', 'Arctic gateway for chasing the aurora borealis, with midnight sun and dramatic fjords.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Nature', 'Aurora', 'Adventure'], 2000, 5000, 'September', 'March', 'Arctic Magic', 95, 45, '500,000', false, ARRAY['Aurora chasing', 'Dog sledding', 'Fjord tours', 'Whale watching']),
('Cinque Terre', 'Italy', 'Five colorful fishing villages connected by coastal trails, offering authentic Italian Riviera charm.', 'https://images.pexels.com/photos/1287460/pexels-photo-1287460.jpeg', ARRAY['Coastal', 'Hiking', 'Village'], 1000, 2500, 'April', 'October', 'Coastal Trails', 93, 70, '2.5 million', false, ARRAY['Hiking', 'Swimming', 'Photography', 'Italian cuisine']),
('Faroe Islands', 'Denmark', 'Remote volcanic islands with dramatic cliffs, grass-roof houses, and untouched Nordic beauty.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Nature', 'Remote', 'Photography'], 1500, 3500, 'May', 'August', 'Nordic Wilderness', 97, 15, '100,000', true, ARRAY['Hiking', 'Bird watching', 'Photography', 'Cultural immersion']),

-- EUROPE - Eastern Europe
('Plitvice Lakes', 'Croatia', 'UNESCO cascade of 16 terraced lakes connected by waterfalls and surrounded by forest.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Nature', 'Waterfalls', 'Hiking'], 300, 800, 'April', 'October', 'Natural Cascades', 94, 60, '1.5 million', false, ARRAY['Walking trails', 'Photography', 'Boat rides', 'Wildlife spotting']),
('esky Krumlov', 'Czech Republic', 'A medieval fairytale town with a magnificent castle, winding streets, and Vltava river.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Medieval', 'Cultural', 'Architecture'], 400, 1000, 'April', 'October', 'Medieval Gem', 96, 40, '1 million', false, ARRAY['Castle tours', 'Rafting', 'Historical walks', 'Local breweries']),
('Tallinn Old Town', 'Estonia', 'Best-preserved medieval city in Europe with cobblestone streets and Gothic spires.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Medieval', 'Cultural', 'Architecture'], 500, 1200, 'May', 'September', 'Medieval Charm', 94, 48, '3 million', false, ARRAY['City walks', 'Castle visits', 'Medieval dining', 'Craft markets']),

-- AMERICAS - North America
('Grand Canyon', 'Arizona, USA', 'One of Earths most awe-inspiring natural wonders, carved by the Colorado River over millions of years.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Nature', 'Adventure', 'Hiking'], 600, 2000, 'March', 'May', 'Natural Wonder', 95, 80, '6 million', false, ARRAY['Hiking', 'Rafting', 'Helicopter tours', 'Sunset watching']),
('Yellowstone', 'Wyoming, USA', 'The worlds first national park, home to geysers, hot springs, wildlife, and dramatic landscapes.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Nature', 'Wildlife', 'Geothermal'], 500, 1800, 'April', 'October', 'Wilderness Icon', 96, 75, '4 million', false, ARRAY['Wildlife watching', 'Geyser viewing', 'Hiking', 'Camping']),
('Yosemite', 'California, USA', 'Granite cliffs, giant sequoias, and thundering waterfalls in a stunning Sierra Nevada valley.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Mountain', 'Nature', 'Climbing'], 400, 1500, 'May', 'September', 'Valley of Giants', 94, 72, '4 million', false, ARRAY['Rock climbing', 'Hiking', 'Waterfalls', 'Photography']),
('New York City', 'New York, USA', 'The city that never sleeps - iconic skyline, Broadway, diverse neighborhoods, and endless energy.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['City', 'Culture', 'Entertainment'], 1500, 5000, 'Year-round', 'Year-round', 'Urban Energy', 78, 95, '65 million', false, ARRAY['Broadway shows', 'Museums', 'Dining', 'Sightseeing']),
('Banff', 'Alberta, Canada', 'Mountain paradise with turquoise lakes, wildlife, and stunning Rocky Mountain scenery.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Mountain', 'Nature', 'Lake'], 800, 2500, 'June', 'September', 'Mountain Paradise', 93, 65, '4 million', false, ARRAY['Hiking', 'Lake visits', 'Wildlife watching', 'Hot springs']),
('Antelope Canyon', 'Arizona, USA', 'Spectacular slot canyon with light beams illuminating sculpted sandstone walls.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Nature', 'Photography', 'Canyon'], 200, 600, 'March', 'October', 'Slot Canyon Magic', 96, 55, '500,000', false, ARRAY['Photography tours', 'Canyon hiking', 'Light beam viewing', 'Navajo culture']),

-- AMERICAS - Central and South America
('Machu Picchu', 'Cusco, Peru', 'The legendary Lost City of the Incas perched high in the Andes, a bucket-list wonder.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Historical', 'Adventure', 'Hiking'], 500, 2000, 'April', 'October', 'Incan Wonder', 98, 82, '1.5 million', false, ARRAY['Inca Trail trek', 'Archaeological tours', 'Photography', 'Spiritual ceremonies']),
('Galpagos Islands', 'Ecuador', 'Wildlife paradise where Darwin developed evolution theory - unique species found nowhere else.', 'https://images.pexels.com/photos/17078916/pexels-photo-17078916.jpeg', ARRAY['Wildlife', 'Nature', 'Diving'], 2500, 6000, 'June', 'November', 'Evolution Lab', 99, 58, '250,000', false, ARRAY['Wildlife watching', 'Snorkeling', 'Diving', 'Naturalist tours']),
('Patagonia', 'Argentina and Chile', 'End of the world wilderness with glaciers, mountains, and pristine wilderness.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Nature', 'Glacier', 'Adventure'], 1000, 3500, 'November', 'March', 'End of World', 97, 40, '500,000', true, ARRAY['Glacier trekking', 'Hiking', 'Wildlife', 'Landscape photography']),
('Costa Rica Cloud Forests', 'Monteverde, Costa Rica', 'Misty forests with incredible biodiversity, hanging bridges, and pristine nature.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Nature', 'Wildlife', 'Eco'], 600, 1800, 'December', 'April', 'Biodiversity Hotspot', 95, 55, '500,000', false, ARRAY['Canopy walks', 'Bird watching', 'Night tours', 'Coffee tours']),
('Antigua Guatemala', 'Guatemala', 'Colonial jewel surrounded by volcanoes, with cobblestone streets and Baroque architecture.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Colonial', 'Cultural', 'Historical'], 400, 1000, 'November', 'April', 'Colonial Beauty', 93, 45, '2 million', false, ARRAY['Spanish classes', 'Volcano hikes', 'Market visits', 'Architecture tours']),
('Iguazu Falls', 'Argentina and Brazil', 'Massive waterfall system spanning two countries with 275 cascades in lush jungle.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Waterfall', 'Nature', 'Adventure'], 500, 1500, 'April', 'October', 'Cascading Wonder', 94, 62, '1.8 million', false, ARRAY['Boat rides', 'Walkway tours', 'Wildlife viewing', 'Helicopter rides']),

-- OCEANIA
('Great Barrier Reef', 'Queensland, Australia', 'Worlds largest coral reef system with incredible marine biodiversity and diving.', 'https://images.pexels.com/photos/1287460/pexels-photo-1287460.jpeg', ARRAY['Diving', 'Nature', 'Marine'], 1500, 4000, 'June', 'October', 'Marine Wonderland', 92, 70, '2 million', false, ARRAY['Diving', 'Snorkeling', 'Island hopping', 'Marine research']),
('Milford Sound', 'New Zealand', 'Dramatic fjord with towering waterfalls, sheer cliffs, and pristine wilderness.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Nature', 'Fjord', 'Scenic'], 600, 1500, 'November', 'March', 'Fjord Majesty', 96, 50, '1 million', false, ARRAY['Cruises', 'Kayaking', 'Hiking', 'Scenic flights']),
('Queenstown', 'New Zealand', 'Adventure capital of the world with bungee jumping, skiing, and stunning lake scenery.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Adventure', 'Lake', 'Mountain'], 800, 2500, 'December', 'February', 'Adventure Hub', 88, 68, '3 million', false, ARRAY['Bungee jumping', 'Skiing', 'Jet boating', 'Wine tasting']),
('Fiji Islands', 'Fiji', '333 tropical islands with crystal waters, coral reefs, and authentic island culture.', 'https://images.pexels.com/photos/1287460/pexels-photo-1287460.jpeg', ARRAY['Beach', 'Island', 'Diving'], 1200, 3500, 'May', 'October', 'Island Paradise', 90, 60, '900,000', false, ARRAY['Snorkeling', 'Diving', 'Island hopping', 'Cultural village visits']),

-- AFRICA
('Serengeti', 'Tanzania', 'Iconic savanna hosting the Great Migration - millions of wildebeest and predators.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Safari', 'Wildlife', 'Nature'], 2000, 6000, 'June', 'October', 'Wildlife Kingdom', 97, 65, '350,000', false, ARRAY['Safari drives', 'Hot air balloon', 'Migration viewing', 'Maasai culture']),
('Victoria Falls', 'Zambia and Zimbabwe', 'The Smoke that Thunders - one of the worlds largest and most spectacular waterfalls.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Waterfall', 'Nature', 'Adventure'], 600, 2000, 'February', 'May', 'Thundering Waters', 94, 58, '1.5 million', false, ARRAY['Waterfall viewing', 'White water rafting', 'Bungee jumping', 'Helicopter rides']),
('Pyramids of Giza', 'Egypt', 'The only surviving Ancient Wonder of the World - legendary pyramids and Sphinx.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Historical', 'Ancient', 'Icon'], 500, 2000, 'October', 'April', 'Ancient Wonder', 93, 85, '14 million', false, ARRAY['Pyramid tours', 'Camel rides', 'Museum visits', 'Nile cruises']),
('Marrakech Medina', 'Morocco', 'Vibrant ancient city with souks, palaces, riads, and sensory overload.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Cultural', 'Bazaar', 'Architecture'], 400, 1500, 'March', 'May', 'Sensory City', 91, 72, '3 million', false, ARRAY['Souk exploring', 'Hammam', 'Cooking classes', 'Desert trips']),

-- MIDDLE EAST
('Petra', 'Jordan', 'The Rose City carved into red cliffs, an archaeological wonder and Jordans treasure.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Historical', 'Archaeology', 'Adventure'], 600, 2000, 'March', 'May', 'Rose Wonder', 98, 75, '1 million', false, ARRAY['Temple exploration', 'Night tours', 'Hiking', 'Photography']),
('Cappadocia', 'Turkey', 'Fairy tale landscape of cave dwellings, rock formations, and legendary hot air balloon rides.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Unique', 'Adventure', 'Cultural'], 500, 1800, 'April', 'October', 'Fairy Chimneys', 95, 68, '3 million', false, ARRAY['Hot air ballooning', 'Cave hotels', 'Underground cities', 'Hiking']),
('Dubai', 'United Arab Emirates', 'Futuristic city with record-breaking architecture, luxury shopping, and desert adventures.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['City', 'Luxury', 'Modern'], 1000, 5000, 'November', 'March', 'Modern Oasis', 82, 88, '16 million', false, ARRAY['Desert safaris', 'Shopping', 'Architecture tours', 'Beach']),

-- Hidden Gems
('Socotra Island', 'Yemen', 'Galapagos of the Indian Ocean with alien-like dragon blood trees and endemic species.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Nature', 'Unique', 'Remote'], 1500, 3000, 'November', 'March', 'Alien Landscape', 100, 5, '10,000', true, ARRAY['Nature exploration', 'Photography', 'Hiking', 'Camping']),
('Svalbard', 'Norway', 'Arctic archipelago with polar bears, midnight sun, northern lights, and global seed vault.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Arctic', 'Wildlife', 'Unique'], 2000, 5000, 'June', 'September', 'Arctic Frontier', 98, 10, '50,000', true, ARRAY['Polar bear viewing', 'Glacier hiking', 'Dog sledding', 'Northern lights']),
('Madagascar', 'Madagascar', 'Evolution laboratory with lemurs, baobabs, and 90 percent endemic wildlife.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Wildlife', 'Nature', 'Adventure'], 800, 2500, 'April', 'October', 'Endemic Paradise', 96, 35, '300,000', true, ARRAY['Lemur watching', 'Beach', 'Hiking', 'Wildlife photography']),
('Salar de Uyuni', 'Bolivia', 'Worlds largest salt flat creating mirror effects and stunning sunset reflections.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Unique', 'Photography', 'Nature'], 600, 1500, 'May', 'November', 'Mirror World', 97, 25, '150,000', true, ARRAY['Photography', '4x4 tours', 'Stargazing', 'Flamingo watching']),
('Rotorua Geothermal', 'New Zealand', 'Geothermal wonderland with geysers, hot pools, and Maori cultural experiences.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Geothermal', 'Cultural', 'Nature'], 500, 1200, 'Year-round', 'Year-round', 'Geothermal Valley', 94, 45, '1 million', false, ARRAY['Geyser viewing', 'Hot springs', 'Maori culture', 'Zorbing']),
('Azores', 'Portugal', 'Remote Atlantic islands with volcanic landscapes, hot springs, and whale watching.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Nature', 'Volcanic', 'Island'], 800, 2000, 'May', 'October', 'Atlantic Gems', 96, 22, '200,000', true, ARRAY['Whale watching', 'Hot springs', 'Hiking', 'Crater lakes']),
('Lofoten Islands', 'Norway', 'Dramatic peaks rising from the sea with fishing villages, midnight sun, and aurora.', 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg', ARRAY['Nature', 'Arctic', 'Photography'], 1200, 3000, 'June', 'September', 'Arctic Beauty', 97, 18, '80,000', true, ARRAY['Photography', 'Hiking', 'Fishing', 'Northern lights']);
